// Generated by windows_modern_shell/generate_actions.py. Do not edit.
#pragma once

struct UwUActionDefinition {
    const wchar_t* title;
    const wchar_t* action;
    const wchar_t* extensions;
    bool folderOnly;
};

inline constexpr UwUActionDefinition kUwUActions[] = {
    {L"3D Model - Convert To GLB", L"MODELGLB", L".obj;.ply;.stl", false},
    {L"3D Model - Convert To OBJ", L"MODELOBJ", L".glb;.ply;.stl", false},
    {L"3D Model - Convert To PLY", L"MODELPLY", L".glb;.obj;.stl", false},
    {L"3D Model - Convert To STL", L"MODELSTL", L".glb;.obj;.ply", false},
    {L"Archive - Extract Here", L"ARCHIVE_EXTRACT_HERE", L".7z;.arj;.bz2;.bzip2;.cab;.dmg;.gz;.gzip;.iso;.lzh;.lzma;.rar;.rpm;.tar;.wim;.xar;.xz;.zip", false},
    {L"Archive - Extract Here and Delete Archive", L"ARCHIVE_EXTRACT_HERE_DELETE", L".7z;.arj;.bz2;.bzip2;.cab;.dmg;.gz;.gzip;.iso;.lzh;.lzma;.rar;.rpm;.tar;.wim;.xar;.xz;.zip", false},
    {L"Archive - Extract to Archive-Named Folder", L"ARCHIVE_EXTRACT_FOLDER", L".7z;.arj;.bz2;.bzip2;.cab;.dmg;.gz;.gzip;.iso;.lzh;.lzma;.rar;.rpm;.tar;.wim;.xar;.xz;.zip", false},
    {L"Archive - Extract to Archive-Named Folder and Delete Archive", L"ARCHIVE_EXTRACT_FOLDER_DELETE", L".7z;.arj;.bz2;.bzip2;.cab;.dmg;.gz;.gzip;.iso;.lzh;.lzma;.rar;.rpm;.tar;.wim;.xar;.xz;.zip", false},
    {L"Archive - Open Archive Manager", L"ARCHIVE_OPEN_UI", L".7z;.arj;.bz2;.bzip2;.cab;.dmg;.gz;.gzip;.iso;.lzh;.lzma;.rar;.rpm;.tar;.wim;.xar;.xz;.zip", false},
    {L"Document - Convert To DOCX from ODT/TXT", L"DOCDOCX", L".odt;.txt", false},
    {L"Document - Convert To DOCX from PDF", L"DOCXFPDF", L".pdf", false},
    {L"Document - Convert To ODT", L"DOCODT", L".docx;.txt", false},
    {L"Document - Convert To PDF", L"DOCPDF", L".docx;.odt;.txt", false},
    {L"Document - Convert To TXT", L"DOCTXT", L".docx;.odt", false},
    {L"Image - Compress By 25%", L"IMAGE_COMPRESS_25", L".jpeg;.jpg;.png;.webp", false},
    {L"Image - Compress By 50%", L"IMAGE_COMPRESS_50", L".jpeg;.jpg;.png;.webp", false},
    {L"Image - Compress By 75%", L"IMAGE_COMPRESS_75", L".jpeg;.jpg;.png;.webp", false},
    {L"Image - Convert To ICO", L"ICO", L".jpeg;.jpg;.png;.raw;.tif;.tiff;.webp", false},
    {L"Image - Convert To JPEG", L"JPEG", L".ico;.jpg;.png;.raw;.tif;.tiff;.webp", false},
    {L"Image - Convert To JPG", L"JPG", L".ico;.jpeg;.png;.raw;.tif;.tiff;.webp", false},
    {L"Image - Convert To PDF", L"PDF", L".ico;.jpeg;.jpg;.png;.raw;.tif;.tiff;.webp", false},
    {L"Image - Convert To PNG", L"PNG", L".ico;.jpeg;.jpg;.raw;.tif;.tiff;.webp", false},
    {L"Image - Convert To TIF", L"TIF", L".jpeg;.jpg;.png;.raw;.tiff;.webp", false},
    {L"Image - Convert To TIFF", L"TIFF", L".jpeg;.jpg;.png;.raw;.tif;.webp", false},
    {L"Image - Convert To WEBP", L"WEBP", L".ico;.jpeg;.jpg;.png;.raw;.tif;.tiff", false},
    {L"Image - Lossless Optimize", L"IMAGE_COMPRESS_LOSSLESS", L".jpeg;.jpg;.png;.webp", false},
    {L"Spreadsheet - Convert To CSV", L"SHEETCSV", L".ods;.tsv;.xls;.xlsb;.xlsm;.xlsx", false},
    {L"Spreadsheet - Convert To ODS", L"SHEETODS", L".csv;.tsv;.xls;.xlsb;.xlsm;.xlsx", false},
    {L"Spreadsheet - Convert To PDF", L"SHEETPDF", L".csv;.ods;.tsv;.xls;.xlsb;.xlsm;.xlsx", false},
    {L"Spreadsheet - Convert To TSV", L"SHEETTSV", L".csv;.ods;.xls;.xlsb;.xlsm;.xlsx", false},
    {L"Spreadsheet - Convert To XLS", L"SHEETXLS", L".csv;.ods;.tsv;.xlsb;.xlsm;.xlsx", false},
    {L"Spreadsheet - Convert To XLSX", L"SHEETXLSX", L".csv;.ods;.tsv;.xls;.xlsb;.xlsm", false},
    {L"Video - Compress By 25%", L"VIDEO_COMPRESS_25", L".avi;.mkv;.mov;.mp4;.webm", false},
    {L"Video - Compress By 50%", L"VIDEO_COMPRESS_50", L".avi;.mkv;.mov;.mp4;.webm", false},
    {L"Video - Compress By 75%", L"VIDEO_COMPRESS_75", L".avi;.mkv;.mov;.mp4;.webm", false},
    {L"Video - Convert To AVI", L"AVI", L".mkv;.mov;.mp4;.webm", false},
    {L"Video - Convert To MKV", L"MKV", L".avi;.mov;.mp4;.webm", false},
    {L"Video - Convert To MOV", L"MOV", L".avi;.mkv;.mp4;.webm", false},
    {L"Video - Convert To MP4", L"MP4", L".avi;.mkv;.mov;.webm", false},
    {L"Video - Convert To WEBM", L"WEBM", L".avi;.mkv;.mov;.mp4", false},
    {L"Video - Lossless Optimize", L"VIDEO_COMPRESS_LOSSLESS", L".avi;.mkv;.mov;.mp4;.webm", false},
    {L"Video/Audio - Convert To Audio OGG", L"OGG", L".avi;.flac;.mkv;.mov;.mp3;.mp4;.opus;.wav;.webm", false},
    {L"Video/Audio - Convert To FLAC", L"FLAC", L".avi;.mkv;.mov;.mp3;.mp4;.ogg;.opus;.wav;.webm", false},
    {L"Video/Audio - Convert To MP3", L"MP3", L".avi;.flac;.mkv;.mov;.mp3;.mp4;.ogg;.opus;.wav;.webm", false},
    {L"Video/Audio - Convert To OPUS", L"OPUS", L".avi;.flac;.mkv;.mov;.mp3;.mp4;.ogg;.wav;.webm", false},
    {L"Video/Audio - Convert To WAV", L"WAV", L".avi;.flac;.mkv;.mov;.mp3;.mp4;.ogg;.opus;.webm", false},
    {L"Archive - Compress Selection to ZIP...", L"ARCHIVE_CREATE_ZIP_PROMPT", L"", false},
    {L"Batch Convert Folder...", L"BATCH_UI_ALL", L"", true},
};

inline constexpr size_t kUwUActionCount =
    sizeof(kUwUActions) / sizeof(kUwUActions[0]);
