from __future__ import annotations

import pathlib
import runpy


ROOT = pathlib.Path(__file__).resolve().parent.parent
OUTPUT = pathlib.Path(__file__).resolve().parent / "generated_actions.h"

CATEGORY_EXTENSIONS = {
    "Video": {".mp4", ".mkv", ".mov", ".avi", ".webm"},
    "Audio": {".mp3", ".wav", ".ogg", ".flac", ".opus"},
    "Image": {".png", ".jpg", ".jpeg", ".webp", ".ico", ".raw", ".tif", ".tiff"},
    "3D Model": {".obj", ".stl", ".ply", ".glb"},
    "Document": {".pdf", ".docx", ".txt", ".odt"},
    "Spreadsheet": {".xlsx", ".xls", ".ods", ".csv", ".xlsb", ".xlsm", ".tsv"},
}

CATEGORY_ORDER = [
    "Image",
    "Video",
    "Audio",
    "Document",
    "Spreadsheet",
    "3D Model",
    "Archive",
]

ARCHIVE_EXTENSIONS = {
    ".7z", ".zip", ".rar", ".tar", ".gz", ".gzip",
    ".bz2", ".bzip2", ".xz", ".wim", ".cab", ".iso",
    ".arj", ".lzh", ".lzma", ".rpm", ".dmg", ".xar",
}

ARCHIVE_ACTIONS = [
    ("Open Archive Manager", "ARCHIVE_OPEN_UI"),
    ("Extract Here", "ARCHIVE_EXTRACT_HERE"),
    ("Extract to Archive-Named Folder", "ARCHIVE_EXTRACT_FOLDER"),
    ("Extract Here and Delete Archive", "ARCHIVE_EXTRACT_HERE_DELETE"),
    ("Extract to Archive-Named Folder and Delete Archive", "ARCHIVE_EXTRACT_FOLDER_DELETE"),
]


def category_for_extension(extension: str) -> str:
    for category, extensions in CATEGORY_EXTENSIONS.items():
        if extension in extensions:
            return category
    return "Other"


def walk_items(items):
    for _, label, action in items:
        if isinstance(action, list):
            yield from walk_items(action)
        else:
            yield str(label), str(action)


def escape_cpp(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    namespace = runpy.run_path(str(ROOT / "file_types.py"))
    file_types = namespace["file_types"]

    actions: dict[str, dict[str, object]] = {}

    for extension, items in file_types.items():
        extension = extension.lower()
        category = category_for_extension(extension)

        for label, action in walk_items(items):
            entry = actions.setdefault(
                action,
                {
                    "label": label,
                    "extensions": set(),
                    "categories": set(),
                },
            )
            entry["extensions"].add(extension)
            entry["categories"].add(category)

    for label, action in ARCHIVE_ACTIONS:
        actions[action] = {
            "label": label,
            "extensions": set(ARCHIVE_EXTENSIONS),
            "categories": {"Archive"},
        }

    provisional_rows = []

    for action, entry in actions.items():
        categories = entry["categories"]
        ordered_categories = [
            category
            for category in CATEGORY_ORDER
            if category in categories
        ]

        if "Other" in categories:
            ordered_categories.append("Other")

        prefix = "/".join(ordered_categories)
        title = entry["label"]

        if prefix:
            title = f"{prefix} - {title}"

        extensions_set = set(entry["extensions"])
        extensions = ";".join(sorted(extensions_set))
        provisional_rows.append((title, action, extensions, extensions_set))

    title_counts = {}
    for title, _, _, _ in provisional_rows:
        title_counts[title.casefold()] = title_counts.get(title.casefold(), 0) + 1

    rows = []
    for title, action, extensions, extensions_set in provisional_rows:
        if title_counts[title.casefold()] > 1:
            sources = "/".join(
                extension.removeprefix(".").upper()
                for extension in sorted(extensions_set)
            )
            title = f"{title} from {sources}"

        rows.append((title.casefold(), title, action, extensions))

    rows.sort()

    lines = [
        "// Generated by windows_modern_shell/generate_actions.py. Do not edit.",
        "#pragma once",
        "",
        "struct UwUActionDefinition {",
        "    const wchar_t* title;",
        "    const wchar_t* action;",
        "    const wchar_t* extensions;",
        "    bool folderOnly;",
        "};",
        "",
        "inline constexpr UwUActionDefinition kUwUActions[] = {",
    ]

    for _, title, action, extensions in rows:
        lines.append(
            '    {L"%s", L"%s", L"%s", false},'
            % (
                escape_cpp(title),
                escape_cpp(action),
                escape_cpp(extensions),
            )
        )

    lines.extend(
        [
            (
                '    {L"Archive - Compress Selection to ZIP...", '
                'L"ARCHIVE_CREATE_ZIP_PROMPT", L"", false},'
            ),
            '    {L"Batch Convert Folder...", L"BATCH_UI_ALL", L"", true},',
            "};",
            "",
            "inline constexpr size_t kUwUActionCount =",
            "    sizeof(kUwUActions) / sizeof(kUwUActions[0]);",
            "",
        ]
    )

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(OUTPUT)
    print(f"Generated {len(rows) + 3} modern context-menu actions.")


if __name__ == "__main__":
    main()
